openslide/openslide-python

- doc/index.rst
- openslide/__init__.py
```console
$ cat 1.py
from collections import Mapping
```
```console
$ python --version
Python 3.8.0
$ python 1.py
1.py:1: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
from collections import Mapping
```
```console
$ python --version
Python 3.9.0a2+
$ python 1.py
Traceback (most recent call last):
File "/private/tmp/openslide-python/1.py", line 1, in <module>
from collections import Mapping
ImportError: cannot import name 'Mapping' from 'collections' (/Users/hugo/.pyenv/versions/3.9-dev/lib/python3.9/collections/__init__.py)
```
Also reported at https://bugzilla.redhat.com/show_bug.cgi?id=1791684.
> Fix ImportError in Python 3.9

- setup.py
https://github.com/pypa/setuptools/issues/65
https://github.com/pypa/setuptools/issues/2017
https://github.com/openslide/openslide/issues/287
untested
> Remove Feature module to match setuptools >=46.0.0

- openslide/lowlevel.py
- tests/__init__.py
- tests/test_openslide.py
The fallback code originally ran if OpenSlide Python was installed `--without-performance`, but setuptools 46 dropped the `Feature` mechanism and #76 removed `--without-performance` from `setup.py`.  There is now no mechanism for providing default-enabled optional features in Python packages.
The fallback case was originally added for Windows users who don't have MSVC installed, but we now distribute precompiled Python wheels for Windows, so it should be okay to just require the compiled module.
> Drop fallback code for missing extension module

- README.rst
- examples/deepzoom/deepzoom_multiserver.py
- examples/deepzoom/deepzoom_server.py
- examples/deepzoom/deepzoom_tile.py
- openslide/__init__.py
- openslide/_convert.c
- openslide/_version.py
- openslide/deepzoom.py
- openslide/lowlevel.py
- setup.py
- tests/__init__.py
- tests/test_base.py
- tests/test_deepzoom.py
- tests/test_imageslide.py
- tests/test_openslide.py
Python 2 reached EOL more than a year ago, taking PIL with it.
Closes #93.
> Drop support for Python 2 and PIL

- openslide/__init__.py
- tests/__init__.py
`pathlib.Path` instances are commonly used, but the `openslide.OpenSlide` class was not compatible with the `pathlib.Path` type. This commit converts the `slide._filename` attribute to a `str` type in `__init__`. This means that the `openslide.OpenSlide` class can now accept a `pathlib.Path` instance.
> Add support for pathlib.Path instances

- README.rst
- doc/index.rst
- openslide/lowlevel.py
Add installation instructions to the docs, hopefully addressing the recurring issues we've seen.  Explain that OpenSlide must be installed separately, point out that it can't be installed with a different full-service package manager than OpenSlide Python, and document the `os.add_dll_directory()` requirement for Python &ge; 3.8 on Windows.  Update the installation section of the README to point to the docs.
Also improve the exception when failing to load the dylib on macOS, and add a descriptive exception when failing to load the DLL on Windows.
Fixes https://github.com/openslide/openslide-python/issues/98.  Fixes https://github.com/openslide/openslide-python/issues/115.
> Add installation instructions to docs; improve exceptions on library load failure

- .github/workflows/python.yml
- examples/deepzoom/deepzoom_tile.py
If our code was specified directly to Python (e.g. we're running as a command-line script), rather than running from a module, `PackageLoader` in jinja2 3.x fails to read our template with:
ValueError: __main__.__spec__ is None
Read the template directly from the filesystem in this case.
Also add a simple `deepzoom_tile.py` CI test.
> examples/deepzoom: fix `./deepzoom_tile.py -r` with jinja2 3.x

- doc/index.rst
- examples/deepzoom/deepzoom_multiserver.py
- openslide/__init__.py
- openslide/lowlevel.py
- tests/__init__.py
- tests/test_imageslide.py
- tests/test_openslide.py
Support the cache management API implemented in https://github.com/openslide/openslide/pull/335.  Sample usage:
```python
import openslide
osr = openslide.OpenSlide("slide.svs")
cache = openslide.OpenSlideCache(256 << 20)
osr.set_cache(cache)
```
> Support OpenSlide cache management API

- doc/jekyll_fix.py
Sphinx 5.x has a temporary JS polyfill, scheduled to be removed in Sphinx 6, whose filename starts with an underscore.  Therefore Jekyll doesn't publish it to the website.  Rename the file and update references.
Also drop support for Sphinx < 1.6, since 1.6.1 was released in May 2017.
> doc: fix Jekyll hiding a JS polyfill with Sphinx 5.x; drop support for Sphinx < 1.6

- .github/workflows/python.yml
Drop workaround for 64-bit `longjmp` crash.
> workflows: update to OpenSlide Windows release 20220811

- .pre-commit-config.yaml
Fixes error:
RuntimeError: The Poetry configuration is invalid:
- [extras.pipfile_deprecated_finder.2] 'pip-shims<=0.3.4' does not match '^[a-zA-Z-_.0-9]+$'
> pre-commit-config: update isort

- openslide/lowlevel.py
Try loading `libopenslide.so.1` or OS-specific equivalent, and fall back to `libopenslide.so.0` if missing.
Also bump minimum version for cache functions to 4.0.0, since OpenSlide 3.5.0 was never released.
For https://github.com/openslide/openslide/pull/413.
> lowlevel: support `libopenslide.so.1` soname

- .github/workflows/python.yml
Current Pillow releases no longer ship 32-bit wheels.  Rather than falling back to a source build, which fails because of missing dependencies, fall back to the latest Pillow that does have a wheel.
> workflows: use latest available Pillow wheel on Windows

- openslide/lowlevel.py
- tests/common.py
- tests/test_base.py
- tests/test_imageslide.py
- tests/test_openslide.py
Add `available` attribute on `lowlevel` functions to indicate whether OpenSlide supports the function, without the need to call it.  Update tests to use this; drop `maybe_supported` decorator.
> lowlevel: add attribute indicating whether a function is available

- examples/deepzoom/deepzoom_multiserver.py
- examples/deepzoom/deepzoom_server.py
- examples/deepzoom/deepzoom_tile.py
optparse is deprecated, and argparse is available on all supported Python versions.
> examples/deepzoom: switch from optparse to argparse

- doc/index.rst
- examples/deepzoom/deepzoom_multiserver.py
- examples/deepzoom/deepzoom_server.py
- examples/deepzoom/deepzoom_tile.py
ICC profiles don't necessarily support all rendering intents, and aren't necessarily optimized for all the intents they do support.  They can also be queried for the rendering intent recommended by the profile creator. Use that by default, instead of absolute colorimetric.
> Default to default rendering intent from slide ICC profile

- .github/ISSUE_TEMPLATE/release.md
The Fedora package has EPEL branches, and we now have an Ubuntu PPA. Update the PPA before sending announce mail so users can upgrade immediately.
> templates/release: add additional package repos

- .github/workflows/python.yml
We're planning to drop 32-bit Windows builds of OpenSlide, so 32-bit wheels will no longer be useful.
Fixes https://github.com/openslide/openslide-python/issues/232.
> workflows: drop 32-bit wheels

- .github/ISSUE_TEMPLATE/release.md
- .github/workflows/python.yml
- .gitignore
- .isort.cfg
- .pre-commit-config.yaml
- .rstcheck.cfg
- MANIFEST.in
- pyproject.toml
- pytest.ini
- setup.py
Switch away from `setup.py` as much as possible.  Drop obsolete `test_suite` and `zip_safe` settings.  Combine multi-word keywords.  Add repo and documentation URLs.  Move tool configurations into `pyproject.toml` where possible.  PEP 621 support requires setuptools &ge; 61.
Build the source tarball and wheels for Linux, macOS, and Windows in GitHub Actions using the Python `build` package.  The Linux wheels support `manylinux1` and above, after postprocessing with `auditwheel`, because the extension module doesn't use libc functions.  The macOS wheels are multi-arch on Python 3.9+.
While we're here, minor release procedure updates: update the Fedora package and check that it propagated to the Copr before announcing the release; additionally announce releases to forum.image.sc.
> Switch to PEP 621 project metadata; build sdist and all wheels in CI

- .github/ISSUE_TEMPLATE/python-bump.md
- .github/workflows/python.yml
- openslide/_convert.c
- setup.py
This allows us to produce forward-compatible wheels and stop building new wheels for every Python minor release.  The buffer protocol API was added to the Limited API in 3.11, so we still need version-specific wheels for releases older than that.
Replace a couple functions that aren't in the Stable API with equivalents that are.
> convert: use Python Limited API on Python 3.11 and above

- .pre-commit-config.yaml
Add some additional hooks.  Drop unnecessary exclusions of GitHub issue templates.
Python 3.8 is now the minimum supported version.
> pre-commit-config: small improvements

- .github/ISSUE_TEMPLATE/release.md
- .github/workflows/python.yml
Use PyPI's [trusted publisher mechanism](https://docs.pypi.org/trusted-publishers/), which is configured to require deploying via a GitHub environment, which is configured to require manual approval.
> workflows: automatically publish releases to PyPI and GitHub

- .github/workflows/python.yml
Make it easier for forks to upload to TestPyPI.
> workflows: get PyPI upload URL from var in GitHub environment

- .github/workflows/python.yml
It's no longer possible for multiple jobs to accumulate results into the same artifact.  Upload a separate artifact for the sdist and each wheel, and have the release job download them all via wildcard.
The sdist and wheels are already compressed, so disable compression in the wrapper Zips.
> workflows: update to artifacts v4

- .github/workflows/python.yml
auditwheel 6.0.0 no longer requires it.
> workflows: skip installing setuptools

- pyproject.toml
Link to [`CHANGELOG.md`](https://github.com/openslide/openslide-python/blob/main/CHANGELOG.md) instead of the [GitHub Releases page](https://github.com/openslide/openslide-python/releases), since it's less noisy.
> pyproject: link to release notes from PyPI page

- .github/workflows/python.yml
rather than hardcoding a version number.
Also use `gh release download` instead of hardcoding the openslide-bin zip URL template.
> workflows: autodetect latest openslide-bin release

- .github/workflows/python.yml
This gets us ARM64 testing and changes the Homebrew installation path.
> workflows: update to macOS 14

- .github/workflows/python.yml
The latter is now an alias for the former.  Switch back so we get future OS updates.
> workflows: switch from `macos-14` to `macos-latest`

- openslide/__init__.py
Hi, I am a user who really enjoys and actively utilizes OpenSlide. I would like to express my gratitude to @bgilbert for creating such an excellent open-source project!
While using the code, I found a small area where I could contribute, so I created a PR with a one-line change. Since the `max()` function can accept iterable objects such as generators, it seems that there is no need to unpack them using an asterisk `*`.
- Refactor code by removing unnecessary unpack operator `*`
> Remove unnecessary unpacking

- .github/workflows/python.yml
- README.md
- doc/index.rst
- openslide/lowlevel.py
Prefer loading OpenSlide from the openslide-bin package if available.
For ease of use, document openslide-bin as the preferred installation option.  Don't document manual installation of openslide-bin binaries on Linux and macOS, since there isn't generally an advantage to doing that, but leave the existing Windows Zip instructions for compatibility and to explain `os.add_dll_directory()`.
Add an explanatory `ModuleNotFoundError` on Linux if OpenSlide is not found.
> Support openslide-bin

- .pre-commit-config.yaml
- doc/jekyll_fix.py
- examples/deepzoom/deepzoom_multiserver.py
- examples/deepzoom/deepzoom_server.py
- examples/deepzoom/deepzoom_tile.py
- openslide/__init__.py
- openslide/deepzoom.py
- openslide/lowlevel.py
- tests/common.py
- tests/test_base.py
- tests/test_deepzoom.py
- tests/test_imageslide.py
- tests/test_openslide.py
Require `from __future__ import annotations` in every Python file that isn't a known config file.  Prep for adding type annotations.
> pre-commit: require PEP 563 type annotations

- .github/workflows/python.yml
Use GitHub's paid support for ARM64 runners, pending the free offering scheduled for later this year.
> workflows: add Linux aarch64 builds

- .pre-commit-config.yaml
- openslide/__init__.py
- openslide/_convert.pyi
- openslide/lowlevel.py
- pyproject.toml
Only support type-checking on Python 3.10+, at least for now.
Prep for #260.  I'll rebase that PR after this lands.
> Add type hints to `_convert` and `lowlevel`; add type-checking infrastructure

- .pre-commit-config.yaml
- openslide/__init__.py
- openslide/deepzoom.py
- pyproject.toml
- tests/test_imageslide.py
Hey folks,
An attempt to address #157 
I've typed the main interface and the deepzoom file, with ignoring type hints for the harder-to-type lowlevel file.
I think I could get there for lowlevel as well but would this suffice in the meantime?
Would have a few conflicts with https://github.com/openslide/openslide-python/pull/243, is that still active?
I've strict typed against 3.8 as per the mypy settings in pyproject.toml. Opted for mypy as that's the tool I'm familiar wth
> Add type hints to `openslide` package

- tests/test_openslide.py
Pillow < 6.2.0 doesn't support any version of Python we still support.
> tests: drop obsolete Pillow version test

- .github/ISSUE_TEMPLATE/python-bump.md
- pyproject.toml
Also ensure the Python-bump checklist bumps the hardcoded Python versions in the Actions workflow.
> pyproject: update for Python 3.13

- doc/conf.py
- doc/index.rst
- openslide/__init__.py
- openslide/deepzoom.py
Document `AbstractSlide`; it's used in the type signature of the `DeepZoomGenerator` constructor because `DeepZoomGenerator` also supports user-supplied `AbstractSlide` subclasses.  Update the `DeepZoomGenerator` description to mention user-provided implementations.
Also several cleanups.
> doc: add type hints

- examples/deepzoom/deepzoom_multiserver.py
- examples/deepzoom/deepzoom_server.py
- examples/deepzoom/deepzoom_tile.py
Give clearer feedback if the argument is invalid.  For the WSGI programs we need to continue enforcing validity outside of argparse, since the value may be set by other means.
> examples/deepzoom: enforce `--format` enum in argparse

- openslide/__init__.py
- openslide/lowlevel.py
Based on, and supersedes, #243.
cc @jaharkes
> Small fixes

- openslide/__init__.py
- openslide/lowlevel.py
If `libopenslide.so.1` fails to load, we want to report that exception too, not just the fact that `libopenslide.so.0` doesn't exist.  Make `try_load()` recursive rather than iterative, allowing Python's exception chaining to handle this automatically.  Reported by @govinda-kamath; thanks!
Also use explicit exception chaining during any conversion of exception types.  This changes Python's exception chain reporting to make it clear that the new exception was not an unrelated failure while handling the original one, but rather the direct cause of it.
> Include all `LoadLibrary()` failures in exception chain

- examples/deepzoom/deepzoom_multiserver.py
- examples/deepzoom/deepzoom_server.py
- examples/deepzoom/deepzoom_tile.py
- tests/common.py
On Python 3.13+, and on all Python versions on Linux, set the default job count to the number of available CPUs.  Otherwise, default to 4 jobs as before.
Also: if OpenSlide Python is type-checked on Windows, `os.add_dll_directory()` will exist and mypy will complain.  Add an extra ignore to fix this.  Mypy understands conditionalizing on `sys.platform` but not on `os.name`, and we want the latter because it exactly corresponds to whether the function exists.
> examples/deepzoom: parallelize `deepzoom_tile` to available CPUs

- .github/workflows/python.yml
- CHANGELOG.md
Current versions of setuptools normalize the filename of the source tarball and of its toplevel directory to `openslide_python-*` per [PEP 625](https://peps.python.org/pep-0625/); see https://github.com/pypa/setuptools/issues/3593. This is an intentional ecosystem-wide change, so adapt to it rather than trying to undo it.
> setuptools 69.3+ normalizes sdist name to `openslide_python`

- MANIFEST.in
- pyproject.toml
- setup.py
When setuptools 61+ is configured via `pyproject.toml`, it defaults to `include-package-data = true`, rather than the historical default of `false`. We don't want wheels to include random files from the package directory, in particular `_convert.c`.  Disable `include-package-data`.
In addition, we were inadvertently relying on setuptools 69+ experimental functionality to include `.pyi` and `py.typed` files in the sdist and `.pyi` files in wheels.  Explicitly configure this.
Move `py.typed` `package-data` declaration from `setup.py` to `pyproject.toml`.
> Fix configuration of package data

- .github/workflows/python.yml
- examples/deepzoom/deepzoom_tile.py
- setup.py
We still need to support building distro packages with older setuptools that doesn't understand PEP 621.  Re-add enough `setup.py` configuration (duplicating `pyproject.toml`) to make older setuptools happy.
Also work around a `FileSystemLoader` bug in Jinja2 < 2.11.0.
> Fix `setup.py install` with old setuptools

- .github/workflows/python.yml
`gh-action-pypi-publish` now writes attestation files to the artifact directory that should not be uploaded to the GitHub release.  Add explicit wildcards for the file extensions we do want to upload.
> workflows: omit `*.publish.attestation` files from release artifacts

- .github/workflows/python.yml
GitHub is [deprecating](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/) the `ubuntu-20.04` image.
Move repo checkout after dependency installation so it can use Git.
> workflows: switch setuptools job to Ubuntu 20.04 container

- .github/workflows/python.yml
Ubuntu 20.04 is exiting standard security support at the end of May. Switch to 22.04, which still has an old enough setuptools.  Stick with the container, rather than using GitHub's `ubuntu-22.04` runner image, for better control over the included software versions.
> workflows: switch setuptools job to Ubuntu 22.04 container

- .github/workflows/python.yml
It appears setup-python's Python 3.8, 3.9, and 3.10 macOS builds are now capable of producing universal binaries.  Stop using the upstream Python 3.9 and 3.10 builds and remove the test exception for 3.8.
The change seems to have happened before we released any macOS wheels, so this won't affect the 3.8 release artifacts.
> workflows: expect macOS universal binaries from setup-python on 3.{8,9,10}

- MANIFEST.in
- README.md
- examples/deepzoom/licenses/LICENSE.jquery
- examples/deepzoom/licenses/LICENSE.openseadragon
- examples/deepzoom/licenses/LICENSE.openseadragon-scalebar
The licenses are included or linked at the top of the JS files, but it's better to also ship them separately.
Also document these licenses in the README.
> examples/deepzoom: add license files for bundled JS

- .github/workflows/python.yml
- .pre-commit-config.yaml
- README.md
- examples/deepzoom/deepzoom_server.py
- openslide/__init__.py
- pyproject.toml
It's EOL.  Ubuntu 20.04 is the last officially-supported distro that uses it, and Ubuntu 20.04 will exit standard security maintenance on May 31.
> Drop support for Python 3.8

- pyproject.toml
Add a [PEP 735](https://peps.python.org/pep-0735/) dependency group that installs a supported version of pytest.  This allows downstream build systems (e.g. Fedora) to autodetect test dependencies.  pip 25.1 allows installing these dependencies with `pip install --group test`.
> pyproject: add dependency group for test deps

- pyproject.toml
Conform with [PEP 639](https://peps.python.org/pep-0639/) by adding links to our license files, using a SPDX license expression to declare our licenses, and dropping the deprecated license Trove classifier.
The new syntax for `project.license` requires setuptools &ge; 77, so this change breaks compatibility with setuptools 61-76.  Users installing from source will be unaffected because the build frontend automatically updates setuptools if required, but Linux distro packaging disallows such updates, so **this change breaks package builds for many current distro versions, including all stable versions of Debian, Fedora, and Ubuntu** as well as Debian testing.
setuptools' deprecation warning claims that the old syntax will be removed on 2026-Feb-18.  If setuptools sticks to this plan, they …
> Switch to PEP 639 license metadata

- openslide/_convert.c
Single-phase initialization is considered legacy.
> convert: switch to multi-phase module initialization
